version: '3.4'

services:
  backend:
    image: mouse-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mouse-backend
    volumes:
      - ./backend:/usr/src/app
    ports: 
      - "8000:8000"
    command: [
      "sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ]