# Generated by Django 5.0.7 on 2024-08-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('future', 'future')], max_length=64, verbose_name='Статус задания'),
        ),
    ]
